# Note: One of the settings don't work, none of them will work

# Colors to be used
colors:
  title: bold yellow
  table:
    header: bold green
    body: cyan  
  text: white
  error: bold red
  players:
    1: bold blue
    2: bold red

# Gui
gui:
  prompt: ">>>"